#
# Copyright (C) 2023 Bruce Chen <a805899926@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for AdguardHome
LUCI_DEPENDS:=+luci-compat +adguardhome

PKG_MAINTAINER:=Bruce Chen <a805899926@gmail.com>
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
