#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Bruce Chen <a805899926@gmail.com>

START=90
STOP=10

USE_PROCD=1
PROG="/usr/bin/dnsproxy"

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}

add_instance() {
	local name="$1"
    
    config_get listen_addr "$s" listen_addr
    config_get listen_port "$s" listen_port
	config_get verbose "$s" verbose

	procd_open_instance "$name"
	procd_set_param command "$PROG"	\
		--listen "$listen_addr" \
		--port "$listen_port" \
		--output "/var/log/dnsproxy-$name.log"
	[ ${verbose} ] && {
		echo "====="
		procd_set_param command --verbose
	}
	for i in "bootstrap" "fallback" "upstream"; do
		config_list_foreach "$name" $i "procd_append_param command --$i"
	done
		
    procd_set_param respawn
	
	procd_close_instance
}

start_instance() {
	local s="$1"
    
    section_enabled "$s" || {
		return 1
	}
    [ ! -d "/var/run" ] && mkdir -p "/var/run"
	add_instance "$s"
}

start_service() {
	local instance="$1"
	local instance_found=0
	
	config_cb() {
		local type="$1"
		local name="$2"
		if [ "$type" = "dnsproxy" ]; then
			if [ -n "$instance" -a "$instance" = "$name" ]; then
				instance_found=1
			fi
		fi
	}

    config_load "dnsproxy"

	if [ -n "$instance" ]; then
		[ "$instance_found" -gt 0 ] || return
		start_instance "$instance"
	else
    	config_foreach start_instance 'dnsproxy'
	fi
}

service_triggers() {
	procd_add_reload_trigger dnsproxy
}
