name: Deploy static

on:
  push:
    paths:
      - 'static/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: czy21/openwrt-builder
      volumes:
        - ${{ vars.OPENWRT_BUILDER_VOLUME }}/:/data/
      options: --user root --privileged --pull always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout firmware-selector-openwrt-org
        uses: actions/checkout@v4
        with: 
          repository: openwrt/firmware-selector-openwrt-org
          path: feeds/firmware-selector-openwrt-org
      
      - name: Setup firmware-selector-openwrt-org config.json
        run: |
          cp -rv static/firmware/* feeds/firmware-selector-openwrt-org/www/
          cd feeds/firmware-selector-openwrt-org/www/
          sed -i "s;%GIT_VERSION%;$(git describe --tags);" index.js

      - name: Deploy firmware-selector-openwrt-org to local
        run: cp -r feeds/firmware-selector-openwrt-org/www/* /data/firmware/

      - name: Deploy downloads-openwrt-org to local
        run: cp -rv static/download/* /data/download/
